### PR TITLE
Support/wagtail 4

### PR DESCRIPTION
**Pull request by nickmoreton**
This improves on https://github.com/unexceptable/wagtail-robots/pull/15

And adds:

- Testing
- Tox envlist for Wagtail <=4.1 and Django <=4.1
- Makefile (for convenience)

### CODE REVIEW

**Comment by victoriachan** [comment]
This looks good. It worked well when I briefly tested on a local build using wagtail `3.0.1` and `4.0.4`.

**Comment by kakulukia** [comment]
Worked like a charm. Its kinda @unexceptable to not merge and release this! :D

**Comment by unexceptable** [comment]
it is indeed unexceptable!

The code for this looks good, am pulling it down and testing it now, if that seems alright I'll merge and release!

**Comment by unexceptable** [comment]
this has now been released as 0.4.0 :)

**Comment by kakulukia** [comment]
thx!

**Pull request merged**
